version: '3'

services: 
  db-app:
    image: mysql:latest
    container_name: database-app
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  phpMyAdmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-app
    ports:
      - 8080:80
    links: 
      - db-app
    depends_on: 
      - db-app